//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:57:50 PM PST 
//


package com.redhat.gss.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A list of zero or more module dependencies.
 *             
 * 
 * <p>Java class for dependenciesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dependenciesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="module" type="{urn:jboss:module:1.3}moduleDependencyType"/>
 *         &lt;element name="system" type="{urn:jboss:module:1.3}systemDependencyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dependenciesType", propOrder = {
    "moduleOrSystem"
})
public class DependenciesType {

    @XmlElements({
        @XmlElement(name = "module", type = ModuleDependencyType.class),
        @XmlElement(name = "system", type = SystemDependencyType.class)
    })
    protected List<Object> moduleOrSystem;

    /**
     * Gets the value of the moduleOrSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moduleOrSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModuleOrSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleDependencyType }
     * {@link SystemDependencyType }
     * 
     * 
     */
    public List<Object> getModuleOrSystem() {
        if (moduleOrSystem == null) {
            moduleOrSystem = new ArrayList<Object>();
        }
        return this.moduleOrSystem;
    }

}
