//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:57:50 PM PST 
//


package com.redhat.gss.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A filter specification, consisting of zero or more filter items.
 *             
 * 
 * <p>Java class for filterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="include" type="{urn:jboss:module:1.3}pathSpecType" minOccurs="0"/>
 *         &lt;element name="exclude" type="{urn:jboss:module:1.3}pathSpecType" minOccurs="0"/>
 *         &lt;element name="include-set" type="{urn:jboss:module:1.3}pathSetType" minOccurs="0"/>
 *         &lt;element name="exclude-set" type="{urn:jboss:module:1.3}pathSetType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterType", propOrder = {
    "includeOrExcludeOrIncludeSet"
})
public class FilterType {

    @XmlElementRefs({
        @XmlElementRef(name = "include-set", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "exclude", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "exclude-set", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "include", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> includeOrExcludeOrIncludeSet;

    /**
     * Gets the value of the includeOrExcludeOrIncludeSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeOrExcludeOrIncludeSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeOrExcludeOrIncludeSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PathSpecType }{@code >}
     * {@link JAXBElement }{@code <}{@link PathSetType }{@code >}
     * {@link JAXBElement }{@code <}{@link PathSpecType }{@code >}
     * {@link JAXBElement }{@code <}{@link PathSetType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getIncludeOrExcludeOrIncludeSet() {
        if (includeOrExcludeOrIncludeSet == null) {
            includeOrExcludeOrIncludeSet = new ArrayList<JAXBElement<?>>();
        }
        return this.includeOrExcludeOrIncludeSet;
    }

}
