//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:57:50 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:jboss:module:1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.redhat.gss.model;
