//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:57:50 PM PST 
//


package com.redhat.gss.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A list of zero or more resource roots for this deployment.
 *             
 * 
 * <p>Java class for resourcesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourcesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="resource-root" type="{urn:jboss:module:1.3}resourceType"/>
 *         &lt;element name="artifact" type="{urn:jboss:module:1.3}artifactType"/>
 *         &lt;element name="native-artifact" type="{urn:jboss:module:1.3}artifactType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourcesType", propOrder = {
    "resourceRootOrArtifactOrNativeArtifact"
})
public class ResourcesType {

    @XmlElementRefs({
        @XmlElementRef(name = "native-artifact", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "artifact", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resource-root", namespace = "urn:jboss:module:1.3", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> resourceRootOrArtifactOrNativeArtifact;

    /**
     * Gets the value of the resourceRootOrArtifactOrNativeArtifact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceRootOrArtifactOrNativeArtifact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceRootOrArtifactOrNativeArtifact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ResourceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ArtifactType }{@code >}
     * {@link JAXBElement }{@code <}{@link ArtifactType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getResourceRootOrArtifactOrNativeArtifact() {
        if (resourceRootOrArtifactOrNativeArtifact == null) {
            resourceRootOrArtifactOrNativeArtifact = new ArrayList<JAXBElement<?>>();
        }
        return this.resourceRootOrArtifactOrNativeArtifact;
    }

}
