//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:57:50 PM PST 
//


package com.redhat.gss.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for systemDependencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="systemDependencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="paths" type="{urn:jboss:module:1.3}pathSetType"/>
 *         &lt;element name="exports" type="{urn:jboss:module:1.3}filterType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="export" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "systemDependencyType", propOrder = {

})
public class SystemDependencyType {

    @XmlElement(required = true)
    protected PathSetType paths;
    protected FilterType exports;
    @XmlAttribute(name = "export")
    protected Boolean export;

    /**
     * Gets the value of the paths property.
     * 
     * @return
     *     possible object is
     *     {@link PathSetType }
     *     
     */
    public PathSetType getPaths() {
        return paths;
    }

    /**
     * Sets the value of the paths property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathSetType }
     *     
     */
    public void setPaths(PathSetType value) {
        this.paths = value;
    }

    /**
     * Gets the value of the exports property.
     * 
     * @return
     *     possible object is
     *     {@link FilterType }
     *     
     */
    public FilterType getExports() {
        return exports;
    }

    /**
     * Sets the value of the exports property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterType }
     *     
     */
    public void setExports(FilterType value) {
        this.exports = value;
    }

    /**
     * Gets the value of the export property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExport() {
        if (export == null) {
            return false;
        } else {
            return export;
        }
    }

    /**
     * Sets the value of the export property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExport(Boolean value) {
        this.export = value;
    }

}
